### PR TITLE
Add Contributions guidelines

### PR DESCRIPTION
**Pull request by rsm23**
Add Contributions guidelines

### CODE REVIEW

**Comment by vibhavagarwal5** [comment]
@aSquare14 pls check this once..
@rsm23 Do enter that 'with each git feature addition - add its description too for better understanding'...

**Comment by rsm23** [comment]
@vibhavagarwal5 ok no problem, I'll edit it.

**Comment by rsm23** [comment]
@vibhavagarwal5 how about this bro?

**Comment by vibhavagarwal5** [comment]
@aSquare14 Check this..looks good to me

**Comment by rsm23** [comment]
@vibhavagarwal5 It's not a subheading it's a title and it needs to be `### Title`

**Pull request merged**
