### PR TITLE
Update resources.md

### PR DESCRIPTION
**Pull request by ShobhitBehl**

### CODE REVIEW

**Comment by vibhavagarwal5** [comment]
@aSquare14 Looks good. Should I merge?

**Comment by aSquare14** [comment]
@vibhavagarwal5 @ShobhitBehl please add it in Alphabetical order. It should be good to Merge then . Thanks for working on it !

**Comment by vibhavagarwal5** [comment]
@ShobhitBehl fox it asap.

**Comment by ShobhitBehl** [comment]
@vibhavagarwal5 Done

**Comment by vibhavagarwal5** [comment]
@aSquare14 m merging it.

**Pull request merged**
