### PR TITLE
better document the "undo rebase" scenario

### PR DESCRIPTION
**Pull request by aaptel**

### CODE REVIEW

**Comment by vibhavagarwal5** [comment]
Close this?

**Comment by aSquare14** [comment]
@vibhavagarwal5  I think first line with link is pretty good ! We can keep that

**Comment by vibhavagarwal5** [comment]
@aaptel Can u please fix the conflicts in this PR and make changes accordingly corresponding to your first line...

**Comment by aaptel** [comment]
I prefer my version sorry :/_

**Pull request closed without merging**
